Changes after first test runs

diff --git a/nuodb/scripts/import-archive b/nuodb/scripts/import-archive
--- a/nuodb/scripts/import-archive
+++ b/nuodb/scripts/import-archive
@@ -5,9 +5,9 @@
 : ${IMPORT_LEVEL:=1}
 
 # If archive IMPORT has been defined, and there is no existing archive, then perform the import
-if [ -n '$IMPORT_LOCAL$IMPORT_REMOTE' -a ! -f "$ARCHIVE_DIR/1.atm" -a "$runningArchives" -eq 0 ]; then
+if [ -n "$IMPORT_LOCAL$IMPORT_REMOTE" -a ! -f "$ARCHIVE_DIR/1.atm" -a "$runningArchives" -eq 0 ]; then
     echo "Importing into empty archive..."
-    [[ -n '$IMPORT_REMOTE' && '$IMPORT_REMOTE' != ?*://?* ]] && echo "ERROR: IMPORT_REMOTE is not a valid URL: $IMPORT_REMOTE - import aborted" && exit 98
+    [[ -n "$IMPORT_REMOTE" && "$IMPORT_REMOTE" != ?*://?* ]] && echo "ERROR: IMPORT_REMOTE is not a valid URL: $IMPORT_REMOTE - import aborted" && exit 98
 
     # clean up any tombstone of the archive for this SM
     if [ -n "$myArchive" ]; then
@@ -18,20 +18,20 @@ if [ -n '$IMPORT_LOCAL$IMPORT_REMOTE' -a ! -f "$ARCHIVE_DIR/1.atm" -a "$runningA
 
     # if IMPORT_REMOTE is set - work out whether to import from existing (IMPORT_LOCAL) cache
     importFromCache='false'
-    if [ -n '$IMPORT_REMOTE' ]; then
-        [ -n '$IMPORT_AUTH' -a '$IMPORT_AUTH' != ':' ] && curlAuth='--user $IMPORT_AUTH'
-        if [ -n '$IMPORT_LOCAL' ]; then
+    if [ -n "$IMPORT_REMOTE" ]; then
+        [ -n "$IMPORT_AUTH" -a "$IMPORT_AUTH" != ':' ] && curlAuth="--user $IMPORT_AUTH"
+        if [ -n "$IMPORT_LOCAL" ]; then
 
             # IMPORT_LOCAL is an empty dir
-            if [ -d '$IMPORT_MOUNT' -a $(ls -1 '$IMPORT_MOUNT' | wc -l) -eq 0 ]; then
+            if [ -d "$IMPORT_MOUNT" -a $(ls -1 "$IMPORT_MOUNT" | wc -l) -eq 0 ]; then
                 echo "Extracting and caching $IMPORT_REMOTE into directory host:$IMPORT_LOCAL..."
-                time curl -k ${curlAuth:-} '$IMPORT_REMOTE' | tar xzf - --strip-components ${IMPORT_LEVEL} -C $IMPORT_MOUNT || exit 98
+                time curl -k ${curlAuth:-} "$IMPORT_REMOTE" | tar xzf - --strip-components ${IMPORT_LEVEL} -C $IMPORT_MOUNT || exit 98
                 importFromCache='true'
 
             # IMPORT_LOCAL is an empty file
-            elif [ ! -s '$IMPORT_MOUNT' ]; then
+            elif [ ! -s "$IMPORT_MOUNT" ]; then
                 echo "Caching $IMPORT_REMOTE into file host:$IMPORT_LOCAL..."
-                time curl -k ${curlAuth:-} '$IMPORT_REMOTE' > '$IMPORT_MOUNT' || exit 98
+                time curl -k ${curlAuth:-} "$IMPORT_REMOTE" > "$IMPORT_MOUNT" || exit 98
                 importFromCache='true'
 
             # IMPORT_LOCAL is not empty - assume it is a valid cache
@@ -44,25 +44,25 @@ if [ -n '$IMPORT_LOCAL$IMPORT_REMOTE' -a ! -f "$ARCHIVE_DIR/1.atm" -a "$runningA
         else
             echo "IMPORT_LOCAL is not set - caching disabled."
             echo "Importing from $IMPORT_REMOTE into $ARCHIVE_DIR..."
-            time curl -k ${curlAuth:-} '$IMPORT_REMOTE' | tar xzf - --strip-components ${IMPORT_LEVEL} -C $ARCHIVE_DIR || exit 98
+            time curl -k ${curlAuth:-} "$IMPORT_REMOTE" | tar xzf - --strip-components ${IMPORT_LEVEL} -C $ARCHIVE_DIR || exit 98
         fi
 
     # IMPORT_REMOTE is not set, so check that IMPORT_LOCAL is not empty
     else
-        [ -f '$IMPORT_MOUNT' -a ! -s '$IMPORT_MOUNT' ] && echo "ERROR: IMPORT_LOCAL file host:$IMPORT_LOCAL is empty." && exit 98
-        [ -d '$IMPORT_MOUNT' -a $(ls -1 '$IMPORT_MOUNT' | wc -l) -eq 0 ] && echo "ERROR: IMPORT_LOCAL directory host:$IMPORT_LOCAL is empty." && exit 98
+        [ -f "$IMPORT_MOUNT" -a ! -s "$IMPORT_MOUNT" ] && echo "ERROR: IMPORT_LOCAL file host:$IMPORT_LOCAL is empty." && exit 98
+        [ -d "$IMPORT_MOUNT" -a $(ls -1 "$IMPORT_MOUNT" | wc -l) -eq 0 ] && echo "ERROR: IMPORT_LOCAL directory host:$IMPORT_LOCAL is empty." && exit 98
         importFromCache='true'
     fi
 
     # IMPORT_LOCAL should now have the correct content - import it into the archive
-    if [ -n '$IMPORT_LOCAL' ]; then
-        [ -n '$IMPORT_REMOTE' -a "$importFromCache" = 'true' -a -s '$IMPORT_MOUNT' ] && echo "Using host:$IMPORT_LOCAL as a cached copy of $IMPORT_REMOTE..."
-        if [ -d '$IMPORT_MOUNT' ]; then
+    if [ -n "$IMPORT_LOCAL" ]; then
+        [ -n "$IMPORT_REMOTE" -a "$importFromCache" = 'true' -a -s "$IMPORT_MOUNT" ] && echo "Using host:$IMPORT_LOCAL as a cached copy of $IMPORT_REMOTE..."
+        if [ -d "$IMPORT_MOUNT" ]; then
             echo "Importing directory host:$IMPORT_LOCAL into $ARCHIVE_DIR..."
             time nuodocker restore archive --origin-dir $IMPORT_MOUNT --restore-dir $ARCHIVE_DIR --db-name "$DB_NAME" --clean-metadata || exit 98
-        elif [ "$importFromCache" = 'true' -a -s '$IMPORT_MOUNT' ]; then
+        elif [ "$importFromCache" = 'true' -a -s "$IMPORT_MOUNT" ]; then
             echo "Importing file host:$IMPORT_LOCAL into $ARCHIVE_DIR..."
-            time tar xf '$IMPORT_MOUNT' --strip-components ${IMPORT_LEVEL} -C "$ARCHIVE_DIR" || exit 98
+            time tar xf "$IMPORT_MOUNT" --strip-components ${IMPORT_LEVEL} -C "$ARCHIVE_DIR" || exit 98
         else
             echo "ERROR: IMPORT_LOCAL has been specified, but host:$IMPORT_LOCAL is not a valid import source - IMPORT_LOCAL must be a directory, an initially empty file, or a cached copy of IMPORT_REMOTE - import aborted..."
             exit 98
@@ -75,7 +75,7 @@ if [ -n '$IMPORT_LOCAL$IMPORT_REMOTE' -a ! -f "$ARCHIVE_DIR/1.atm" -a "$runningA
     echo "Imported data looks good: $(ls -l $ARCHIVE_DIR | head -n 5)"
 
     # if the archive was not imported from a dir, then clean the meta-data in the archive
-    if [ ! -d '$IMPORT_MOUNT' ]; then
+    if [ ! -d "$IMPORT_MOUNT" ]; then
         nuodocker restore archive --origin-dir "$ARCHIVE_DIR" --restore-dir "$ARCHIVE_DIR" --db-name "$DB_NAME" --clean-metadata || exit 99
     fi
 fi
