Reimplement all timeouts and gates with the nuodocker timeouts. Add new IMPORT_TIMEOUT variable. Add and improve logging and diagnostics. Refactor raftstate cleanup into new 'remove-zombie' script.

diff --git a/nuodb/scripts/start-nuosm b/nuodb/scripts/start-nuosm
--- a/nuodb/scripts/start-nuosm
+++ b/nuodb/scripts/start-nuosm
@@ -4,28 +4,33 @@
 : ${LOGDIR:=/var/log/nuodb}
 PATH=$PATH:/usr/local/scripts
 
+me="$(basename $0)"
+
 echo "starting SM..."
-echo "=================================="
 
 # do not proceed if the admin layer has failed to become ready
-msg=$(nuocmd check servers --timeout ${STARTUP_TIMEOUT} --check-converged --check-active)
-if [ $? -ne 0 ]; then
-    echo "ERROR: Timed out waiting for admin layer to be ready: $msg"
-    exit 98
-fi
+# msg=$(nuocmd check servers --timeout ${STARTUP_TIMEOUT} --check-converged --check-active)
+# if [ $? -ne 0 ]; then
+#     echo "$me: ERROR: Timed out waiting for admin layer to be ready: $msg"
+#     exit 98
+# fi
 
-nuocmd show domain
-echo "PEER_ADDRESS=$PEER_ADDRESS"
-nuocmd get servers
+# echo "$me: AP is ready..."
+# echo "$me: $(nuocmd show domain)"
+# echo "$me: PEER_ADDRESS=$PEER_ADDRESS"
+# echo "$me: $(nuocmd get servers)"
 
 # shutdown and delete any zombie engine processes (TE or SM)
-nuocmd shutdown server-processes --server-id "${PEER_ADDRESS}" --db-name "$DB_NAME" --evict --timeout 0
+# nuocmd shutdown server-processes --server-id "${PEER_ADDRESS}" --db-name "$DB_NAME" --evict --timeout 0
+
+# remove any zombie process matching the engine that is about to be started
+remove-zombie SM $HOSTNAME
 
 # set up the archive dir
-echo "ARCHIVE_DIR=$ARCHIVE_DIR"
+echo "$me: ARCHIVE_DIR=$ARCHIVE_DIR"
 
 mkdir -p $ARCHIVE_DIR
-[ $? -ne 0 ] && echo "Error creating $ARCHIVE_DIR: $?" && exit 98
+[ $? -ne 0 ] && echo "$0: Error creating $ARCHIVE_DIR: $?" && exit 98
 
 # check for stranded archive definitions - eg from a previous failed startup
 nuocmd show archives --db-name $DB_NAME
@@ -51,6 +56,9 @@ import-archive || exit $?
 
 # start the SM
 nuodocker start sm \
+    --servers-ready-timeout $((STARTUP_TIMEOUT / 2)) \
+    --database-restore-timeout ${RESTORE_TIMEOUT:-$STARTUP_TIMEOUT} \
+    --processes-ready-timeout $((STARTUP_TIMEOUT / 2)) \
     --db-name "$DB_NAME" \
     --server-id "${PEER_ADDRESS}" \
     --dba-user "$DB_USER" \
diff --git a/nuodb/scripts/start-nuote b/nuodb/scripts/start-nuote
--- a/nuodb/scripts/start-nuote
+++ b/nuodb/scripts/start-nuote
@@ -2,24 +2,35 @@
 #
 # start a nuote
 : ${LOGDIR:=/var/log/nuodb}
+PATH=$PATH:/usr/local/scripts
+
+me="$(basename $0)"
 
 echo "Starting TE..."
 
-sleepTime=0
-sleepQuantum=5
-while [ -z "$(nuocmd get processes --db-name $DB_NAME | grep 'state=RUNNING')" -o $? -ne 0 ] ; do
-    if [ $sleepTime -ge $STARTUP_TIMEOUT ]; then
-        echo "Timed out waiting for database startup ($sleepTime sec)..."
-        exit 97
-    fi
+# do not proceed if the admin layer has failed to become ready
+# msg=$(nuocmd check servers --timeout ${STARTUP_TIMEOUT} --check-converged --check-active)
+# if [ $? -ne 0 ]; then
+#     echo "$me: ERROR: Timed out waiting for admin layer to be ready: $msg"
+#     exit 98
+# fi
 
-    echo "Waiting for confirmation that database $DB_NAME is started..."
-    sleep $sleepQuantum
-    sleepTime=$(( sleepTime + sleepQuantum ))
-    [ $sleepTime -gt 30 -a $sleepQuantum -lt $((STARTUP_TIMEOUT / 2)) ] && sleepQuantum=$(( sleepQuantum + 30 ))
-done
+# echo "$me: AP ready..."
+
+# remove any zombie process matching the engine that is about to be started
+remove-zombie TE $HOSTNAME
+
+# wait for at least 1 SM to be running
+# if [ -n "$(nuocmd check database --db-name $DB_NAME --check-running --wait-for-acks --timeout ${STARTUP_TIMEOUT})" -o $? -ne 0 ]; then
+#     echo "$me: ERROR: Timed out waiting for database startup ($STARTUP_TIMEOUT sec)..."
+#     exit 97
+# fi
 
 nuodocker start te \
+    --servers-ready-timeout $((STARTUP_TIMEOUT / 2)) \
+    --database-restore-timeout ${RESTORE_TIMEOUT:-$STARTUP_TIMEOUT} \
+    --database-created-timeout $((STARTUP_TIMEOUT / 2)) \
+    --processes-ready-timeout $((STARTUP_TIMEOUT / 2)) \
     --db-name "$DB_NAME" \
     --server-id "${PEER_ADDRESS}" \
     --options "alt-address ${EXTERNAL_ADDRESS}" \
